name: Build and Test
on: [push, pull_request]
permissions:
  contents: read

jobs:
  build:
    name: Go CI
    strategy:
      matrix:
        go: ["1.19", "1.20"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Prepare env.
      - name: Set up Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 #v3.5.0
        with:
          go-version: ${{ matrix.go }}
      - name: Install Linters
        run: "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.51.2"
        shell: bash
      - name: Set git config to please linters
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      # Test repository.
      - name: Check out source
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c #v3.3.0
      - name: Test
        run: sh ./run_tests.sh
